runtime: php # language & version of the app
env: flex # let app engine know we use flexible environment

runtime_config:
  document_root: public #folder where index.php is

env_variables:
  ## Put production environment variables here.
  ## "facade/ignition": "^2.0",
  APP_NAME: "C.A.B.L.E"
  APP_ENV: local
  APP_KEY: base64:3Mz/MGMzQL5rnxdgjaVDI9vBEdxyxC6hFEVep/Jh9sI=
  APP_DEBUG: true
  APP_URL: "/"
  APP_LOG: daily
  # APP_STORAGE: /tmp
  # VIEW_COMPILED_PATH: /tmp
  BROADCAST_DRIVER: pusher
  CACHE_DRIVER: database
  QUEUE_CONNECTION: sync
  QUEUE_DRIVER: database
  ## Session Configs
  SESSION_DRIVER: database
  SESSION_LIFETIME: 120
  ## Laravel Mix Configs
  MIX_APP_URL: "${APP_URL}"
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
  ## Log Channel for bugs
  # LOG_CHANNEL: stackdriver
  LOG_CHANNEL: stack
  ## Database Configs
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: cable
  DB_USERNAME: root
  DB_PASSWORD: ##echohellO000
  DB_SOCKET: "/cloudsql/root-user"
  ## Mail Configs
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: 2525
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: null
  MAIL_FROM_NAME: "${APP_NAME}"
  GOOGLE_VISION_PROJECT_ID: cable-project-1

#we need this for the flex environment
beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: cable-project-1:us-central1:root-user